### ISSUE TITLE
`architectures` Didn't Work

### ISSUE THREAD

**Issue by east4ming** [QueraTeam/ansible-github#1]
## Problem

Hi, I installed and use the colletion like this in my task:
```yaml
- name: Download rage(rust age)
  quera.github.install_from_github:
    repo: str4d/rage
    asset_regex: rage_.*\.deb
    version_command: rage --version
    move_rules:
      - src_regex: rage_.*\.deb
        dst: /tmp/rage.deb
        mode: 0755
```
My arch is "x86_64", and the rage assets are :

```
rage-musl_0.10.0-1_amd64.deb
rage-musl_0.10.0-1_arm64.deb
rage-musl_0.10.0-1_armhf.deb
rage-v0.10.0-arm64-linux.tar.gz
rage-v0.10.0-armv7-linux.tar.gz
rage-v0.10.0-x86_64-darwin.tar.gz
rage-v0.10.0-x86_64-linux.tar.gz
rage-v0.10.0-x86_64-windows.zip
rage_0.10.0-1_amd64.deb
rage_0.10.0-1_arm64.deb
rage_0.10.0-1_armhf.deb
```

Only these match `asset_regex: rage_.*\.deb`:

```
rage_0.10.0-1_amd64.deb
rage_0.10.0-1_arm64.deb
rage_0.10.0-1_armhf.deb
```

If it works like the help docs: 

```
you don't need
to specify OS (darwin, linux, ...) and architecture (x86_64, amd64, aarch64, arm64, ...)
in your regex (just write `.*` in place of them). This module tries to narrow down
assets based on the system's OS and CPU architecture.
```

But, it didn't work, it reported error:

```log
Couldn't select a unique asset.
```

## Workaround

I workaround by this: (add architecture in `asset_regex` )

```yaml
- name: Download rage(rust age)
  quera.github.install_from_github:
    repo: str4d/rage
    asset_regex: rage_.*amd64\.deb
    version_command: rage --version
    move_rules:
      - src_regex: rage_.*amd64\.deb
        dst: /tmp/rage.deb
        mode: 0755
  when: ansible_architecture == "x86_64"
```

And it works.

## Solution

So, can you help me to resolve this problem?
Thank you.
