### ISSUE TITLE
install neovim does not work

### ISSUE THREAD

**Issue by Susensio** [QueraTeam/ansible-github#4]
Hello,
I'm trying to use this module to install neovim from github, with no luck nor any debug messages to know what happened:

```
- name: NVIM stable is installed
  become: true
  quera.github.install_from_github:
    repo: neovim/neovim
    asset_regex: nvim\-linux64\.tar\.gz
    version_command: nvim --version
    move_rules:
      - src_regex: nvim
        dst: /usr/local/bin
        mode: 0755
  tags:
    - install
    - nvim
```

which results in

```
TASK [nvim : NVIM stable is installed] *******************************************************************************************************************
task path: /tmp/ansible/roles/nvim/tasks/main.yml:34
ok: [localhost] => changed=false
  invocation:
    module_args:
      asset_arch_mapping: {}
      asset_regex: nvim\-linux64\.tar\.gz
      move_rules:
      - dst: /usr/local/bin
        mode: 493
        src_regex: nvim
      repo: neovim/neovim
      tag: latest
      version_command: nvim --version
      version_file: null
      version_regex: null
```

and `/usr/local/bin` contains nothing
What could be failing?
